### ISSUE TITLE
Clean up branches and merge into main

### ISSUE THREAD

**Issue by VivianBass** [asishallab-group/Tensor-Omics#23]
***In GitLab by @asishallab on Jun 13, 2025, 12:50 GMT+2:***

# Clean up branches and merge into `main`

## 📁 Directory Structure (with `fpm` Integration)

```
yourproject/
├── README.md
├── fpm.toml
├── src/
│   ├── core.f90
│   ├── utils.f90
│   └── bindings.f90             # Optional: C-bindings for R/Python
├── test/
│   └── test_utils.f90
├── build/                       # fpm or manual shared library output
│   └── yourlib.so
├── include/                     # Headers for C/C++ or other languages
│   ├── tensor_omics.h
│   └── ...
├── Rpkg/
│   ├── R/
│   │   └── interface.R
│   ├── man/
│   ├── src/
│   │   └── yourlib.so           # Copied .so from build/
│   ├── DESCRIPTION
│   └── NAMESPACE
└── pypkg/
    ├── yourmodule/
    │   ├── __init__.py
    │   └── yourlib.so           # Copied .so from build/
    ├── setup.py
    └── README.md
```

---

## 🛠 `fpm.toml` (Fortran Package Definition)

```toml
name = "yourproject"
version = "0.1.0"
license = "MIT"
author = "Your Name"
maintainer = "you@example.com"
[build]
auto-executables = false
auto-tests = true
auto-examples = false

[library]
source-dir = "src"
build-script = "scripts/build_shared.sh"

[install]
library = true

[compiler]
flags = ["-O3", "-march=native", "-ffast-math", "-funroll-loops", "-fopenmp-simd"] // -O3 -march=native -funroll-loops -ffast-math -fopenmp -ftree-vectorize -fopt-info-vec-optimized

```

```
[build]
auto-executables = true
auto-tests = true
auto-examples = true

[compiler]
# For gfortran or ifort/ifx
flags = [
  "-O3",                   # Full optimization
  "-march=native",         # Use native CPU instructions
  "-funroll-loops",        # Better loop performance
  "-ffast-math",           # Accept small IEEE trade-offs
  "-fopenmp",              # Enable OpenMP threading and SIMD
  "-fopenmp-simd",         # Enforce SIMD directives
  "-Wall",                 # Show all warnings
  "-Wextra",               # Even more warnings
]

```

For Intel compilers (`ifx` or `ifort`):

```toml
flags = ["-O3", "-xHost", "-qopenmp-simd", "-unroll", "-ipo"]
```

## ⚙️ `scripts/build_shared.sh` (to be called by fpm)

```bash
#!/bin/bash
mkdir -p ../build
gfortran -O3 -march=native -ffast-math -funroll-loops -flto \
  -fopenmp -fPIC -shared src/*.f90 -o ../build/yourlib.so
```

> ⚠️ You can modify this script to use `ifort` or `ifx`:

```bash
ifx -O3 -xHost -qopenmp -qopt-report=5 -shared ...
```

---

## 🚀 Recommended Compiler Flags (GCC/gfortran)

These ensure **maximum speed** on modern CPUs with SIMD, vectorization, and loop optimizations:

```bash
-O3                            # Aggressive optimizations
-march=native                 # Optimize for the local CPU
-ffast-math                   # Allow unsafe math for speed
-flto                         # Link-time optimization
-funroll-loops                # Unroll loops to reduce overhead
-fopenmp                      # Use OpenMP for threading
-fPIC                         # Required for shared library
-shared                       # Build as shared object
```

---

## 🧪 Testing with `fpm`

Create tests in `test/`:

```fortran
program test_utils
  use yourmodule
  implicit none
  call assert_equal(2+2, 4, "Basic sanity check")
end program
```

Then run:

```bash
fpm test
```

---

## 🔄 Integrating with R and Python

1. After building:

   ```bash
   cp build/yourlib.so Rpkg/src/
   cp build/yourlib.so pypkg/yourmodule/
   ```

2. Call R and Python integrations as discussed before:

   * In R: `.Fortran("subroutine_name", ...)`
   * In Python: `import yourmodule.yourlib as mod`

**Assignees:** @schroederaaron, luka.faensen, @VivianBass

*Migrated from GitLab: https://gitlab.rlp.net/a.hallab/tensor-omics/-/work_items/22*
